[package]
name = "webby"
version = "0.1.0"
authors = ["Hirad Pourtahmasbi <git@hirad.codes>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
rocket_contrib = "0.4.7"
